# Generated by Django 4.2.21 on 2026-02-06 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_cars_deposit_cars_doors_cars_engine_volume_and_more'),
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars', verbose_name='Автомобіль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Обране',
                'verbose_name_plural': 'Обрані',
                'db_table': 'favorite',
                'unique_together': {('user', 'car')},
            },
        ),
    ]
