# Generated by Django 4.2.21 on 2026-03-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
        ('cars', '0005_cars_deposit_cars_doors_cars_engine_volume_and_more'),
        ('users', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('damage', 'Пошкодження авто'), ('dtp', 'ДТП (Аварія)'), ('breakdown', 'Технічна поломка'), ('other', 'Інше')], max_length=20, verbose_name='Тип події')),
                ('description', models.TextField(verbose_name='Опис проблеми')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_photos/', verbose_name='Фото доказ')),
                ('status', models.CharField(choices=[('pending', 'Очікує розгляду'), ('processing', 'В процесі'), ('resolved', 'Вирішено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name="Пов'язане замовлення")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Звіт про інцидент',
                'verbose_name_plural': 'Звіти про інциденти',
                'db_table': 'incident_report',
            },
        ),
        migrations.CreateModel(
            name='FineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума штрафу')),
                ('reason', models.TextField(verbose_name='Причина штрафу (стаття/опис)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата виписки штрафу')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars', verbose_name='Автомобіль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафи',
                'db_table': 'fine_notification',
            },
        ),
    ]
