# Generated by Django 4.2.21 on 2026-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_incidentreport_finenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема листа')),
                ('content', models.TextField(verbose_name='Текст листа (можна HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletters/', verbose_name='Зображення (опціонально)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Відправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата відправки')),
            ],
            options={
                'verbose_name': 'Розсилка',
                'verbose_name_plural': 'Розсилки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='Підписаний на розсилку'),
        ),
    ]
