# Generated by Django 4.2.21 on 2026-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newsletter_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='target_emails',
            field=models.TextField(blank=True, help_text='Введіть адреси через кому (наприклад: test@gmail.com, example@mail.com)', null=True, verbose_name='Список конкретних Email'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='use_target_emails',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено — лист піде лише на адреси нижче. Якщо вимкнено — усім підписникам.', verbose_name='Відправити тільки на вказані адреси'),
        ),
    ]
