version: '3.8'

services:
  db:
    image: postgres:15
    container_name: car_rental_db
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: home
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # --- НОВИЙ СЕРВІС: REDIS ---
  redis:
    image: redis:7-alpine
    container_name: car_rental_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: car_rental_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=car_rental_db
      - DB_USER=home
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0  # Посилання на Redis
    depends_on:
      - db
      - redis

  # --- НОВИЙ СЕРВІС: CELERY WORKER ---
  celery:
    build: .
    container_name: car_rental_celery
    # Команда запускає воркера, який "слухає" задачі
    command: celery -A car_rental worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DB_NAME=car_rental_db
      - DB_USER=home
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data: