# Generated by Django 4.2.21 on 2025-05-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_sesion_key_cart_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_key',
            new_name='sesion_key',
        ),
    ]
