# Generated by Django 4.2.21 on 2025-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_session_key_cart_sesion_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sesion_key',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
