# Generated by Django 4.2.21 on 2025-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ('id',), 'verbose_name': 'Машину', 'verbose_name_plural': 'Машини'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Машина'),
        ),
    ]
