# Generated by Django 4.2.21 on 2025-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_options_alter_cars_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=7, verbose_name='Депозит $'),
        ),
        migrations.AddField(
            model_name='cars',
            name='doors',
            field=models.IntegerField(default=4, verbose_name='Кількість дверей'),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="Об'єм двигуна (л)"),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Витрата палива'),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гібрид'), ('electric', 'Електро')], default='petrol', max_length=20, verbose_name='Тип палива'),
        ),
        migrations.AddField(
            model_name='cars',
            name='has_air_conditioning',
            field=models.BooleanField(default=True, verbose_name='Кондиціонер'),
        ),
        migrations.AddField(
            model_name='cars',
            name='min_age',
            field=models.IntegerField(default=25, verbose_name='Мінімальний вік водія'),
        ),
        migrations.AddField(
            model_name='cars',
            name='min_experience',
            field=models.IntegerField(default=1, verbose_name='Мінімальний стаж водіння (років)'),
        ),
        migrations.AddField(
            model_name='cars',
            name='seats',
            field=models.IntegerField(default=5, verbose_name='Кількість місць'),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механічна'), ('automatic', 'Автомат'), ('semi_auto', 'Робот')], default='manual', max_length=20, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Знижка %'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна за добу'),
        ),
    ]
