# Generated by Django 4.2.21 on 2025-05-13 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_alter_cars_options_alter_cars_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення бронювання')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата початку оренди')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата зікінченян оренди')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Потрібна доставка')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адреса доставки')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='Оплата при отриманні')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('status', models.CharField(default='Опрацьовується', max_length=50, verbose_name='Статус замовлення')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'order',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна')),
                ('period', models.PositiveIntegerField(default=0, verbose_name='Термін')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення бронювання')),
                ('car', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Орендовану машину',
                'verbose_name_plural': 'Орендовані машини',
                'db_table': 'order_item',
                'ordering': ('id',),
            },
        ),
    ]
