# Generated by Django 4.2.21 on 2025-09-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
    ]
